# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1.xci
# IP: The module: 'fir_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1.xci
# IP: The module: 'fir_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
