# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property constrs_type UCF [current_fileset -constrset]
add_files c:/CHALMERS/DAT096/DAT096/ADCDAC/filtercoeff.coe
add_files C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.runs/fir_compiler_0_synth_1/fir_compiler_0.dcp
set_property used_in_implementation false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.runs/fir_compiler_0_synth_1/fir_compiler_0.dcp]
set_property use_blackbox_stub false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.runs/fir_compiler_0_synth_1/fir_compiler_0.dcp]

read_ip c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC.xci
set_property used_in_implementation false [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC.xci]

read_ip c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/DMC/DMC.xci
set_property used_in_implementation false [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/DMC/DMC.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/DMC/DMC.xci]

read_verilog c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_stub.v
read_vhdl {
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_min_area_pkg.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1_synth_comp.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1_pkg.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1_defaults.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_getinit_pkg.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/xbip_utils_v3_0/hdl/xcc_utils_v3_0.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/xbip_utils_v3_0/hdl/xbip_utils_v3_0_pkg.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/fir_compiler_v7_1/hdl/global_pkg.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/fir_compiler_v7_1/hdl/fir_compiler_v7_1_viv_comp.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/fir_compiler_v7_1/hdl/fir_compiler_v7_1_comp.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/fir_compiler_v7_1/hdl/components.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/axi_utils_v2_0/hdl/global_util_pkg.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/axi_utils_v2_0/hdl/axi_utils_v2_0_pkg.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/ADC/ADC.srcs/sources_1/ip/fir_compiler_0/axi_utils_v2_0/hdl/axi_utils_comps.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/new/Throughput_top.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/new/DAC_buffer.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/new/buffercontrol.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/new/ADC_TOP.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/new/ADC_buffer.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/DAC/top.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/imports/DAC/PWM.vhd
}
set_property webtalk.parent_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.data/wt [current_project]
set_property parent.project_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado [current_project]
synth_design -top Throughput_top -part xc7a100tcsg324-1
write_checkpoint Throughput_top.dcp
report_utilization -file Throughput_top_utilization_synth.rpt -pb Throughput_top_utilization_synth.pb
