# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC.xci
# IP: The module: 'ADC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC_OOC.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC.xci
# IP: The module: 'ADC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC_OOC.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC_vivado/ADC_vivado.srcs/sources_1/ip/ADC/ADC.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
