######################################################################
##
## Filename: Throughput_top_wave.do
## Created on: Mon Feb 24 12:07:44 2014
##
##  Auto generated by Vivado for Behavioral Simulation
##
##  You may want to edit this file to control the simulation
##
######################################################################
add wave *
add wave /glbl/GSR
