# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/ADC_TOP.xdc

# IP: ip/DMC/DMC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMC || ORIG_REF_NAME==DMC}]
