# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.runs/DMC_synth_1/DMC.dcp
set_property used_in_implementation false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.runs/DMC_synth_1/DMC.dcp]
set_property use_blackbox_stub false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.runs/DMC_synth_1/DMC.dcp]
read_verilog c:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.srcs/sources_1/ip/DMC/DMC_stub.v
read_vhdl {
  C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.srcs/sources_1/imports/DAC/PWM.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.srcs/sources_1/imports/DAC/modules.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.srcs/sources_1/imports/DAC/top.vhd
}
read_xdc C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.srcs/constrs_1/imports/DAC_Vivado/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.srcs/constrs_1/imports/DAC_Vivado/Nexys4_Master.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado/DAC_Vivado.data/wt [current_project]
set_property parent.project_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC_Vivado [current_project]
synth_design -top top -part xc7a100tcsg324-1
write_checkpoint top.dcp
report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb
