######################################################################
##
## Filename: dummyapb.do
## Created on: Mon Mar 31 13:56:54 2014
##
##  Auto generated by Vivado for Post-implementation Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the simulation directory and will not be removed on
##  subsequent simulation flow runs from Vivado.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#

#
# Create work library
#
vlib work

#
# Map libraries
#

#
# Design sources
#
vcom -work work "C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.sim/sim_1/impl/func/dummyapb_func_impl.vhd"



#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps -L secureip -lib work dummyapb

#
# Source wave do file
#
do {dummyapb_wave.do}

#
# Set the window types
#
view wave
view structure
view signals

#
# Source user do file (UDO)
#
do {dummyapb.udo}

#
# Run simulation for this time
#
run 1000ns


#
# End
#
