######################################################################
##
## Filename: dummyapb_wave.do
## Created on: Mon Mar 31 13:56:54 2014
##
##  Auto generated by Vivado for Post-implementation Simulation
##
##  You may want to edit this file to control the simulation
##
######################################################################
add wave *
