# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param iopl.placeGlobalClockInstsInIOPlacer 0
  set_param iopl.placeRegionalClockInstsInIOPlacer 0
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property used_in_implementation false [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.data/wt [current_project]
set_property parent.project_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4 [current_project]
synth_design -top fir_compiler_0 -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all fir_compiler_0
write_checkpoint -noxdef fir_compiler_0.dcp
report_utilization -file fir_compiler_0_utilization_synth.rpt -pb fir_compiler_0_utilization_synth.pb
if { [catch {
  file copy -force C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.runs/fir_compiler_0_synth_1/fir_compiler_0.dcp c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.dcp
  write_verilog -force -mode synth_stub c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_stub.v
  write_verilog -force -mode funcsim c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_funcsim.v
  write_vhdl -force -mode funcsim c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC4/ADC4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
