
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'leon3mp.ucf'
####################################################################################

## This file is a general .ucf for the Nexys4 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used signals according to the project

## Clock signal
#Bank = 35, Pin name = IO_L12P_T1_MRCC_35,					Sch name = CLK100MHZ
set_property PACKAGE_PIN E3 [get_ports clk]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:9
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk' has been applied to the port object 'clk'.
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:11
create_clock -period 10.000 -name clk [get_ports clk]

## Switches
#Bank = 34, Pin name = IO_L21P_T3_DQS_34,					Sch name = SW0
set_property PACKAGE_PIN U9 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
#Bank = 34, Pin name = IO_25_34,							Sch name = SW1
set_property PACKAGE_PIN U8 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
#Bank = 34, Pin name = IO_L23P_T3_34,						Sch name = SW2
set_property PACKAGE_PIN R7 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
#Bank = 34, Pin name = IO_L19P_T3_34,						Sch name = SW3
set_property PACKAGE_PIN R6 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
#Bank = 34, Pin name = IO_L19N_T3_VREF_34,					Sch name = SW4
set_property PACKAGE_PIN R5 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
#Bank = 34, Pin name = IO_L20P_T3_34,						Sch name = SW5
set_property PACKAGE_PIN V7 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
#Bank = 34, Pin name = IO_L20N_T3_34,						Sch name = SW6
set_property PACKAGE_PIN V6 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#Bank = 34, Pin name = IO_L10P_T1_34,						Sch name = SW7
set_property PACKAGE_PIN V5 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#Bank = 34, Pin name = IO_L8P_T1-34,						Sch name = SW8
set_property PACKAGE_PIN U4 [get_ports {sw[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#Bank = 34, Pin name = IO_L9N_T1_DQS_34,					Sch name = SW9
set_property PACKAGE_PIN V2 [get_ports {sw[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#Bank = 34, Pin name = IO_L9P_T1_DQS_34,					Sch name = SW10
set_property PACKAGE_PIN U2 [get_ports {sw[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#Bank = 34, Pin name = IO_L11N_T1_MRCC_34,					Sch name = SW11
set_property PACKAGE_PIN T3 [get_ports {sw[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
#Bank = 34, Pin name = IO_L17N_T2_34,						Sch name = SW12
set_property PACKAGE_PIN T1 [get_ports {sw[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
#Bank = 34, Pin name = IO_L11P_T1_SRCC_34,					Sch name = SW13
set_property PACKAGE_PIN R3 [get_ports {sw[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
#Bank = 34, Pin name = IO_L14N_T2_SRCC_34,					Sch name = SW14
set_property PACKAGE_PIN P3 [get_ports {sw[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
#Bank = 34, Pin name = IO_L14P_T2_SRCC_34,					Sch name = SW15
set_property PACKAGE_PIN P4 [get_ports {sw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

## LEDs
#Bank = 34, Pin name = IO_L24N_T3_34,						Sch name = LED0
set_property PACKAGE_PIN T8 [get_ports {Led[0]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:66
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Led[0]' has been applied to the port object 'Led[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Led[0]}]
#Bank = 34, Pin name = IO_L21N_T3_DQS_34,					Sch name = LED1
set_property PACKAGE_PIN V9 [get_ports {Led[1]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:69
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Led[1]' has been applied to the port object 'Led[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Led[1]}]
#Bank = 34, Pin name = IO_L24P_T3_34,						Sch name = LED2
set_property PACKAGE_PIN R8 [get_ports {Led[2]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:72
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Led[2]' has been applied to the port object 'Led[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Led[2]}]
#Bank = 34, Pin name = IO_L23N_T3_34,						Sch name = LED3
set_property PACKAGE_PIN T6 [get_ports {Led[3]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:75
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Led[3]' has been applied to the port object 'Led[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Led[3]}]
#Bank = 34, Pin name = IO_L12P_T1_MRCC_34,					Sch name = LED4
set_property PACKAGE_PIN T5 [get_ports {Led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[4]}]
#Bank = 34, Pin name = IO_L12N_T1_MRCC_34,					Sch	name = LED5
set_property PACKAGE_PIN T4 [get_ports {Led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[5]}]
#Bank = 34, Pin name = IO_L22P_T3_34,						Sch name = LED6
set_property PACKAGE_PIN U7 [get_ports {Led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[6]}]
#Bank = 34, Pin name = IO_L22N_T3_34,						Sch name = LED7
set_property PACKAGE_PIN U6 [get_ports {Led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[7]}]
#Bank = 34, Pin name = IO_L10N_T1_34,						Sch name = LED8
set_property PACKAGE_PIN V4 [get_ports {Led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[8]}]
#Bank = 34, Pin name = IO_L8N_T1_34,						Sch name = LED9
set_property PACKAGE_PIN U3 [get_ports {Led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[9]}]
#Bank = 34, Pin name = IO_L7N_T1_34,						Sch name = LED10
set_property PACKAGE_PIN V1 [get_ports {Led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[10]}]
#Bank = 34, Pin name = IO_L17P_T2_34,						Sch name = LED11
set_property PACKAGE_PIN R1 [get_ports {Led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[11]}]
#Bank = 34, Pin name = IO_L13N_T2_MRCC_34,					Sch name = LED12
set_property PACKAGE_PIN P5 [get_ports {Led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[12]}]
#Bank = 34, Pin name = IO_L7P_T1_34,						Sch name = LED13
set_property PACKAGE_PIN U1 [get_ports {Led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[13]}]
#Bank = 34, Pin name = IO_L15N_T2_DQS_34,					Sch name = LED14
set_property PACKAGE_PIN R2 [get_ports {Led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[14]}]
#Bank = 34, Pin name = IO_L15P_T2_DQS_34,					Sch name = LED15
set_property PACKAGE_PIN P2 [get_ports {Led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Led[15]}]

#NET "RGB1_Red"			LOC = "K5"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L5P_T0_34,						Sch name = LED16_R
#NET "RGB1_Green"		LOC = "F13"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L5P_T0_AD9P_15,					Sch name = LED16_G
#NET "RGB1_Blue"		LOC = "F6"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L19N_T3_VREF_35,					Sch name = LED16_B
#NET "RGB2_Red"			LOC = "K6"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_0_34,								Sch name = LED17_R
#NET "RGB2_Green"		LOC = "H6"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_24P_T3_35,						Sch name =  LED17_G
#NET "RGB2_Blue"		LOC = "L16"	| IOSTANDARD = "LVCMOS33";		#Bank = CONFIG, Pin name = IO_L3N_T0_DQS_EMCCLK_14,			Sch name = LED17_B

## 7 segment display
#NET "seg<0>"			LOC = "L3"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L2N_T0_34,						Sch name = CA
#NET "seg<1>"			LOC = "N1"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L3N_T0_DQS_34,					Sch name = CB
#NET "seg<2>"			LOC = "L5"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L6N_T0_VREF_34,					Sch name = CC
#NET "seg<3>"			LOC = "L4"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L5N_T0_34,						Sch name = CD
#NET "seg<4>"			LOC = "K3"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L2P_T0_34,						Sch name = CE
#NET "seg<5>"			LOC = "M2"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L4N_T0_34,						Sch name = CF
#NET "seg<6>"			LOC = "L6"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L6P_T0_34,						Sch name = CG

#NET "dp"				LOC = "M4"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L16P_T2_34,						Sch name = DP

#NET "an<0>"			LOC = "N6"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L18N_T2_34,						Sch name = AN0
#NET "an<1>"			LOC = "M6"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L18P_T2_34,						Sch name = AN1
#NET "an<2>"			LOC = "M3"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L4P_T0_34,						Sch name = AN2
#NET "an<3>"			LOC = "N5"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L13_T2_MRCC_34,					Sch name = AN3
#NET "an<4>"			LOC = "N2"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L3P_T0_DQS_34,					Sch name = AN4
#NET "an<5>"			LOC = "N4"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L16N_T2_34,						Sch name = AN5
#NET "an<6>"			LOC = "L1"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L1P_T0_34,						Sch name = AN6
#NET "an<7>"			LOC = "M1"	| IOSTANDARD = "LVCMOS33";		#Bank = 34, Pin name = IO_L1N_T034,							Sch name = AN7

## Buttons
#Bank = 15, Pin name = IO_L3P_T0_DQS_AD1P_15,				Sch name = CPU_RESET
set_property PACKAGE_PIN C12 [get_ports btnCpuResetn]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:143
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnCpuResetn' has been applied to the port object 'btnCpuResetn'.
set_property IOSTANDARD LVCMOS33 [get_ports btnCpuResetn]
#Bank = 15, Pin name = IO_L11N_T1_SRCC_15,					Sch name = BTNC
#set_property PACKAGE_PIN E16 [get_ports {btn[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
#Bank = 15, Pin name = IO_L14P_T2_SRCC_15,					Sch name = BTNU
#set_property PACKAGE_PIN F15 [get_ports {btn[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
#Bank = CONFIG, Pin name = IO_L15N_T2_DQS_DOUT_CSO_B_14,	Sch name = BTNL
#set_property PACKAGE_PIN T16 [get_ports {btn[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]
#Bank = 14, Pin name = IO_L21P_T3_DQS_14,					Sch name = BTND
#set_property PACKAGE_PIN V10 [get_ports {btn[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
#Bank = 14, Pin name = IO_25_14,							Sch name = BTNR
#set_property PACKAGE_PIN R10 [get_ports {btn[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn[4]}]

## Pmod Header JA
#NET "JA<0>"			LOC = "B13"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L1N_T0_AD0N_15,					Sch name = JA1
#NET "JA<1>"			LOC = "F14"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L5N_T0_AD9N_15,					Sch name = JA2
#NET "JA<2>"			LOC = "D17"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L16N_T2_A27_15,					Sch name = JA3
#NET "JA<3>"			LOC = "E17"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L16P_T2_A28_15,					Sch name = JA4
#NET "JA<4>"			LOC = "G13"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_0_15,								Sch name = JA7
#NET "JA<5>"			LOC = "C17"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L20N_T3_A19_15,					Sch name = JA8
#NET "JA<6>"			LOC = "D18"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L21N_T3_A17_15,					Sch name = JA9
#NET "JA<7>"			LOC = "E18"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L21P_T3_DQS_15,					Sch name = JA10

#Pmod Header JB
#Bank = 15, Pin name = IO_L15N_T2_DQS_ADV_B_15,				Sch name = JB1
#set_property PACKAGE_PIN G14 [get_ports {JB[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[0]}]
#Bank = 14, Pin name = IO_L13P_T2_MRCC_14,					Sch name = JB2
#set_property PACKAGE_PIN P15 [get_ports {JB[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[1]}]
#Bank = 14, Pin name = IO_L21N_T3_DQS_A06_D22_14,			Sch name = JB3
#set_property PACKAGE_PIN V11 [get_ports {JB[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[2]}]
#Bank = CONFIG, Pin name = IO_L16P_T2_CSI_B_14,				Sch name = JB4
#set_property PACKAGE_PIN V15 [get_ports {JB[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[3]}]
#Bank = 15, Pin name = IO_25_15,							Sch name = JB7
#set_property PACKAGE_PIN K16 [get_ports {JB[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[4]}]
#Bank = CONFIG, Pin name = IO_L15P_T2_DQS_RWR_B_14,			Sch name = JB8
#set_property PACKAGE_PIN R16 [get_ports {JB[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[5]}]
#Bank = 14, Pin name = IO_L24P_T3_A01_D17_14,				Sch name = JB9
#set_property PACKAGE_PIN T9 [get_ports {JB[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[6]}]
#Bank = 14, Pin name = IO_L19N_T3_A09_D25_VREF_14,			Sch name = JB10
#set_property PACKAGE_PIN U11 [get_ports {JB[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JB[7]}]

## Pmod Header JC
#NET "JC<0>"			LOC = "K2"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L23P_T3_35,						Sch name = JC1
#NET "JC<1>"			LOC = "E7"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L6P_T0_35,						Sch name = JC2
#NET "JC<2>"			LOC = "J3"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L22P_T3_35,						Sch name = JC3
#NET "JC<3>"			LOC = "J4"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L21P_T3_DQS_35,					Sch name = JC4
#NET "JC<4>"			LOC = "K1"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L23N_T3_35,						Sch name = JC7
#NET "JC<5>"			LOC = "E6"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L5P_T0_AD13P_35,					Sch name = JC8
#NET "JC<6>"			LOC = "J2"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L22N_T3_35,						Sch name = JC9
#NET "JC<7>"			LOC = "G6"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L19P_T3_35,						Sch name = JC10

## Pmod Header JD
#NET "JD<0>"			LOC = "H4"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L21N_T2_DQS_35,					Sch name = JD1
#NET "JD<1>"			LOC = "H1"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L17P_T2_35,						Sch name = JD2
#NET "JD<2>"			LOC = "G1"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L17N_T2_35,						Sch name = JD3
#NET "JD<3>"			LOC = "G3"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L20N_T3_35,						Sch name = JD4
#NET "JD<4>"			LOC = "H2"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L15P_T2_DQS_35,					Sch name = JD7
#NET "JD<5>"			LOC = "G4"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L20P_T3_35,						Sch name = JD8
#NET "JD<6>"			LOC = "G2"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L15N_T2_DQS_35,					Sch name = JD9
#NET "JD<7>"			LOC = "F3"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L13N_T2_MRCC_35,					Sch name = JD10

##Pmod Header JXADC
##Bank = 15, Pin name = IO_L9P_T1_DQS_AD3P_15,				Sch name = XADC1_P -> XA1_P
set_property IOSTANDARD LVCMOS33 [get_ports vauxp3]
##Bank = 15, Pin name = IO_L8P_T1_AD10P_15,					Sch name = XADC2_P -> XA2_P
#set_property PACKAGE_PIN A15 [get_ports {JXADC[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JXADC[1]}]
##Bank = 15, Pin name = IO_L7P_T1_AD2P_15,					Sch name = XADC3_P -> XA3_P
#set_property PACKAGE_PIN B16 [get_ports {JXADC[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JXADC[2]}]
##Bank = 15, Pin name = IO_L10P_T1_AD11P_15,					Sch name = XADC4_P -> XA4_P
#set_property PACKAGE_PIN B18 [get_ports {JXADC[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JXADC[3]}]
##Bank = 15, Pin name = IO_L9N_T1_DQS_AD3N_15,				Sch name = XADC1_N -> XA1_N
set_property PACKAGE_PIN A14 [get_ports vauxn3]
set_property IOSTANDARD LVCMOS33 [get_ports vauxn3]
##Bank = 15, Pin name = IO_L8N_T1_AD10N_15,					Sch name = XADC2_N -> XA2_N
#set_property PACKAGE_PIN A16 [get_ports {JXADC[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JXADC[5]}]
##Bank = 15, Pin name = IO_L7N_T1_AD2N_15,					Sch name = XADC3_N -> XA3_N
#set_property PACKAGE_PIN B17 [get_ports {JXADC[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JXADC[6]}]
##Bank = 15, Pin name = IO_L10N_T1_AD11N_15,					Sch name = XADC4_N -> XA4_N
#set_property PACKAGE_PIN A18 [get_ports {JXADC[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {JXADC[7]}]

## VGA Connector
#NET "vgaRed<0>"		LOC = "A3"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L8N_T1_AD14N_35,					Sch name = VGA_R0
#NET "vgaRed<1>"		LOC = "B4"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L7N_T1_AD6N_35,					Sch name = VGA_R1
#NET "vgaRed<2>"		LOC = "C5"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L1N_T0_AD4N_35,					Sch name = VGA_R2
#NET "vgaRed<3>"		LOC = "A4"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L8P_T1_AD14P_35,					Sch name = VGA_R3
#NET "vgaBlue<0>"		LOC = "B7"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L2P_T0_AD12P_35,					Sch name = VGA_B0
#NET "vgaBlue<1>"		LOC = "C7"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L4N_T0_35,						Sch name = VGA_B1
#NET "vgaBlue<2>"		LOC = "D7"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L6N_T0_VREF_35,					Sch name = VGA_B2
#NET "vgaBlue<3>"		LOC = "D8"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L4P_T0_35,						Sch name = VGA_B3
#NET "vgaGreen<0>"		LOC = "C6"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L1P_T0_AD4P_35,					Sch name = VGA_G0
#NET "vgaGreen<1>"		LOC = "A5"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L3N_T0_DQS_AD5N_35,				Sch name = VGA_G1
#NET "vgaGreen<2>"		LOC = "B6"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L2N_T0_AD12N_35,					Sch name = VGA_G2
#NET "vgaGreen<3>"		LOC = "A6"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L3P_T0_DQS_AD5P_35,				Sch name = VGA_G3
#NET "Hsync"			LOC = "B11"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L4P_T0_15,						Sch name = VGA_HS
#NET "Vsync"			LOC = "B12"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L3N_T0_DQS_AD1N_15,				Sch name = VGA_BVS

## Micro SD Connector
#NET "sdReset"			LOC = "E2"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L14P_T2_SRCC_35,					Sch name = SD_RESET
#NET "sdCD"				LOC = "A1"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L9N_T1_DQS_AD7N_35,				Sch name = SD_CD
#NET "sdSCK"			LOC = "B1"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L9P_T1_DQS_AD7P_35,				Sch name = SD_SCK
#NET "sdCmd"			LOC = "C1"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L16N_T2_35,						Sch name = SD_CMD
#NET "sdData<0>"		LOC = "C2"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L16P_T2_35,							Sch name = SD_DAT0
#NET "sdData<1>" 		LOC = "E1"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L18N_T2_35,						Sch name = SD_DAT1
#NET "sdData<2>"		LOC = "F1"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L18P_T2_35,						Sch name = SD_DAT2
#NET "sdData<3>"		LOC = "D2"  | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L14N_T2_SRCC_35,					Sch name = SD_DAT3

## Accelerometer
#NET "aclMISO"			LOC = "D13"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L6N_T0_VREF_15,					Sch name = ACL_MISO
#NET "aclMOSI"			LOC = "B14"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L2N_T0_AD8N_15,					Sch name = ACL_MOSI
#NET "aclSCK"			LOC = "D15"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L12P_T1_MRCC_15,					Sch name = ACL_SCLK
#NET "aclSS"			LOC = "C15"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L12N_T1_MRCC_15,					Sch name = ACL_CSN
#NET "aclInt1"			LOC = "C16"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L20P_T3_A20_15,					Sch name = ACL_INT1
#NET "aclInt2"			LOC = "E15"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L11P_T1_SRCC_15,					Sch name = ACL_INT2

## Temperature Sensor
#NET "tmpSCL"			LOC = "F16"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L14N_T2_SRCC_15,					Sch name = TMP_SCL
#NET "tmpSDA"			LOC = "G16"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L13N_T2_MRCC_15,					Sch name = TMP_SDA
#NET "tmpInt"			LOC = "D14"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L1P_T0_AD0P_15,					Sch name = TMP_INT
#NET "tmpCT"			LOC = "C14"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L1N_T0_AD0N_15,					Sch name = TMP_CT

## Omnidirectional Microphone
#NET "micClk"			LOC = "J5"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_25_35,								Sch name = M_CLK
#NET "micData"			LOC = "H5"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L24N_T3_35,						Sch name = M_DATA
#NET "micLRSel"			LOC = "F5"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_0_35,								Sch name = M_LRSEL

## PWM Audio Amplifier
#NET "ampPWM"			LOC = "A11"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L4N_T0_15,						Sch name = AUD_PWM
#NET "ampSD"			LOC = "D12"	| IOSTANDARD = "LVCMOS33";		#Bank = 15, Pin name = IO_L6P_T0_15,						Sch name = AUD_SD
##PWM Audio Amplifier
##Bank = 15, Pin name = IO_L4N_T0_15,						Sch name = AUD_PWM
set_property PACKAGE_PIN A11 [get_ports ampPWM]
set_property IOSTANDARD LVCMOS33 [get_ports ampPWM]
##Bank = 15, Pin name = IO_L6P_T0_15,						Sch name = AUD_SD
set_property PACKAGE_PIN D12 [get_ports ampSD]
set_property IOSTANDARD LVCMOS33 [get_ports ampSD]

## USB-RS232 Interface
#Bank = 35, Pin name = IO_L7P_T1_AD6P_35,					Sch name = UART_TXD_IN
set_property PACKAGE_PIN C4 [get_ports RsRx]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:262
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RsRx' has been applied to the port object 'RsRx'.
set_property IOSTANDARD LVCMOS33 [get_ports RsRx]
#Bank = 35, Pin name = IO_L11N_T1_SRCC_35,					Sch name = UART_RXD_OUT
set_property PACKAGE_PIN D4 [get_ports RsTx]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:265
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RsTx' has been applied to the port object 'RsTx'.
set_property IOSTANDARD LVCMOS33 [get_ports RsTx]
#NET "RsCts"			LOC = "D3"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L12N_T1_MRCC_35,					Sch name = UART_CTS
#NET "RsRts"			LOC = "E5"	| IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L5N_T0_AD13N_35,					Sch name = UART_RTS

## USB HID (PS/2)
#NET "PS2Clk"			LOC = "F4"	| PULLUP | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L13P_T2_MRCC_35,					Sch name = PS2_CLK
#NET "PS2Data"			LOC = "B2"	| PULLUP | IOSTANDARD = "LVCMOS33";		#Bank = 35, Pin name = IO_L10N_T1_AD15N_35,					Sch name = PS2_DATA

## SMSC Ethernet PHY
#Bank = 16, Pin name = IO_L11P_T1_SRCC_16,					Sch name = ETH_MDC
set_property PACKAGE_PIN C9 [get_ports PhyMdc]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:276
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyMdc' has been applied to the port object 'PhyMdc'.
set_property IOSTANDARD LVCMOS33 [get_ports PhyMdc]
#Bank = 16, Pin name = IO_L14N_T2_SRCC_16,					Sch name = ETH_MDIO
set_property PACKAGE_PIN A9 [get_ports PhyMdio]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:279
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyMdio' has been applied to the port object 'PhyMdio'.
set_property IOSTANDARD LVCMOS33 [get_ports PhyMdio]
#Bank = 35, Pin name = IO_L10P_T1_AD15P_35,					Sch name = ETH_RSTN
set_property PACKAGE_PIN B3 [get_ports PhyRstn]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:282
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyRstn' has been applied to the port object 'PhyRstn'.
set_property IOSTANDARD LVCMOS33 [get_ports PhyRstn]
#Bank = 16, Pin name = IO_L6N_T0_VREF_16,					Sch name = ETH_CRSDV
set_property PACKAGE_PIN D9 [get_ports PhyCrs]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:285
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyCrs' has been applied to the port object 'PhyCrs'.
set_property IOSTANDARD LVCMOS33 [get_ports PhyCrs]
#Bank = 16, Pin name = IO_L13N_T2_MRCC_16,					Sch name = ETH_RXERR
set_property PACKAGE_PIN C10 [get_ports PhyRxEr]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:288
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyRxEr' has been applied to the port object 'PhyRxEr'.
set_property IOSTANDARD LVCMOS33 [get_ports PhyRxEr]
#Bank = 16, Pin name = IO_L19N_T3_VREF_16,					Sch name = ETH_RXD0
set_property PACKAGE_PIN D10 [get_ports {PhyRxd[0]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:291
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyRxd[0]' has been applied to the port object 'PhyRxd[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {PhyRxd[0]}]
#Bank = 16, Pin name = IO_L13P_T2_MRCC_16,					Sch name = ETH_RXD1
set_property PACKAGE_PIN C11 [get_ports {PhyRxd[1]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:294
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyRxd[1]' has been applied to the port object 'PhyRxd[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {PhyRxd[1]}]
#Bank = 16, Pin name = IO_L11N_T1_SRCC_16,					Sch name = ETH_TXEN
set_property PACKAGE_PIN B9 [get_ports PhyTxEn]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:297
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyTxEn' has been applied to the port object 'PhyTxEn'.
set_property IOSTANDARD LVCMOS33 [get_ports PhyTxEn]
#Bank = 16, Pin name = IO_L14P_T2_SRCC_16,					Sch name = ETH_TXD0
set_property PACKAGE_PIN A10 [get_ports {PhyTxd[0]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:300
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyTxd[0]' has been applied to the port object 'PhyTxd[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {PhyTxd[0]}]
#Bank = 16, Pin name = IO_L12N_T1_MRCC_16,					Sch name = ETH_TXD1
set_property PACKAGE_PIN A8 [get_ports {PhyTxd[1]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:303
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyTxd[1]' has been applied to the port object 'PhyTxd[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {PhyTxd[1]}]
#Bank = 35, Pin name = IO_L11P_T1_SRCC_35,					Sch name = ETH_REFCLK
set_property PACKAGE_PIN D5 [get_ports PhyClk50Mhz]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:306
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PhyClk50Mhz' has been applied to the port object 'PhyClk50Mhz'.
set_property IOSTANDARD LVCMOS33 [get_ports PhyClk50Mhz]
#NET "PhyIntn"			LOC = "B8"	| IOSTANDARD = "LVCMOS33";		#Bank = 16, Pin name = IO_L12P_T1_MRCC_16,					Sch name = ETH_INTN

## Quad SPI Flash
#NET "QspiSCK"			LOC = "E9"	| IOSTANDARD = "LVCMOS33";		#Bank = CONFIG, Pin name = CCLK_0,							Sch name = QSPI_SCK
#NET "QspiDB<0>"			LOC = "K17"	| IOSTANDARD = "LVCMOS33";		#Bank = CONFIG, Pin name = IO_L1P_T0_D00_MOSI_14,			Sch name = QSPI_DQ0
#NET "QspiDB<1>"			LOC = "K18"	| IOSTANDARD = "LVCMOS33";		#Bank = CONFIG, Pin name = IO_L1N_T0_D01_DIN_14,			Sch name = QSPI_DQ1
#NET "QspiDB<2>"			LOC = "L14"	| IOSTANDARD = "LVCMOS33";		#Bank = CONFIG, Pin name = IO_L20_T0_D02_14,				Sch name = QSPI_DQ2
#NET "QspiDB<3>"			LOC = "M14"	| IOSTANDARD = "LVCMOS33";		#Bank = CONFIG, Pin name = IO_L2P_T0_D03_14,				Sch name = QSPI_DQ3
#NET "QspiCSn"			LOC = "L13"	| IOSTANDARD = "LVCMOS33";		#Bank = CONFIG, Pin name = IO_L15N_T2_DQS_DOUT_CSO_B_14,	Sch name = QSPI_CSN

## Cellular RAM
#Bank = 14, Pin name = IO_L14N_T2_SRCC_14,					Sch name = CRAM_CLK
set_property PACKAGE_PIN T15 [get_ports RamClk]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:320
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamClk' has been applied to the port object 'RamClk'.
set_property IOSTANDARD LVCMOS33 [get_ports RamClk]
#Bank = 14, Pin name = IO_L23P_T3_A03_D19_14,				Sch name = CRAM_ADVN
set_property PACKAGE_PIN T13 [get_ports RamAdv]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:323
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamAdv' has been applied to the port object 'RamAdv'.
set_property IOSTANDARD LVCMOS33 [get_ports RamAdv]
#Bank = 14, Pin name = IO_L4P_T0_D04_14,					Sch name = CRAM_CEN
set_property PACKAGE_PIN L18 [get_ports RamCE]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:326
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamCE' has been applied to the port object 'RamCE'.
set_property IOSTANDARD LVCMOS33 [get_ports RamCE]
#Bank = 15, Pin name = IO_L19P_T3_A22_15,					Sch name = CRAM_CRE
set_property PACKAGE_PIN J14 [get_ports RamCRE]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:329
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamCRE' has been applied to the port object 'RamCRE'.
set_property IOSTANDARD LVCMOS33 [get_ports RamCRE]
#Bank = 15, Pin name = IO_L15P_T2_DQS_15,					Sch name = CRAM_OEN
set_property PACKAGE_PIN H14 [get_ports RamOE]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:332
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamOE' has been applied to the port object 'RamOE'.
set_property IOSTANDARD LVCMOS33 [get_ports RamOE]
#Bank = 14, Pin name = IO_0_14,								Sch name = CRAM_WEN
set_property PACKAGE_PIN R11 [get_ports RamWE]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:335
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamWE' has been applied to the port object 'RamWE'.
set_property IOSTANDARD LVCMOS33 [get_ports RamWE]
#Bank = 15, Pin name = IO_L24N_T3_RS0_15,					Sch name = CRAM_LBN
set_property PACKAGE_PIN J15 [get_ports RamLB]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:338
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamLB' has been applied to the port object 'RamLB'.
set_property IOSTANDARD LVCMOS33 [get_ports RamLB]
#Bank = 15, Pin name = IO_L17N_T2_A25_15,					Sch name = CRAM_UBN
set_property PACKAGE_PIN J13 [get_ports RamUB]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:341
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RamUB' has been applied to the port object 'RamUB'.
set_property IOSTANDARD LVCMOS33 [get_ports RamUB]
#NET "RamWait"			LOC = "T14"	| IOSTANDARD = "LVCMOS33";		#Bank = 14, Pin name = IO_L14P_T2_SRCC_14,					Sch name = CRAM_WAIT

#Bank = 14, Pin name = IO_L5P_T0_DQ06_14,					Sch name = CRAM_DQ0
set_property PACKAGE_PIN R12 [get_ports {data[0]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:346
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[0]' has been applied to the port object 'data[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
#Bank = 14, Pin name = IO_L19P_T3_A10_D26_14,				Sch name = CRAM_DQ1
set_property PACKAGE_PIN T11 [get_ports {data[1]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:349
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[1]' has been applied to the port object 'data[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
#Bank = 14, Pin name = IO_L20P_T3_A08)D24_14,				Sch name = CRAM_DQ2
set_property PACKAGE_PIN U12 [get_ports {data[2]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:352
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[2]' has been applied to the port object 'data[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
#Bank = 14, Pin name = IO_L5N_T0_D07_14,					Sch name = CRAM_DQ3
set_property PACKAGE_PIN R13 [get_ports {data[3]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:355
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[3]' has been applied to the port object 'data[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
#Bank = 14, Pin name = IO_L17N_T2_A13_D29_14,				Sch name = CRAM_DQ4
set_property PACKAGE_PIN U18 [get_ports {data[4]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:358
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[4]' has been applied to the port object 'data[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
#Bank = 14, Pin name = IO_L12N_T1_MRCC_14,					Sch name = CRAM_DQ5
set_property PACKAGE_PIN R17 [get_ports {data[5]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:361
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[5]' has been applied to the port object 'data[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
#Bank = 14, Pin name = IO_L7N_T1_D10_14,					Sch name = CRAM_DQ6
set_property PACKAGE_PIN T18 [get_ports {data[6]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:364
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[6]' has been applied to the port object 'data[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
#Bank = 14, Pin name = IO_L7P_T1_D09_14,					Sch name = CRAM_DQ7
set_property PACKAGE_PIN R18 [get_ports {data[7]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:367
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[7]' has been applied to the port object 'data[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
#Bank = 15, Pin name = IO_L22N_T3_A16_15,					Sch name = CRAM_DQ8
set_property PACKAGE_PIN F18 [get_ports {data[8]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:370
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[8]' has been applied to the port object 'data[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[8]}]
#Bank = 15, Pin name = IO_L22P_T3_A17_15,					Sch name = CRAM_DQ9
set_property PACKAGE_PIN G18 [get_ports {data[9]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:373
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[9]' has been applied to the port object 'data[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[9]}]
#Bank = 15, Pin name = IO_IO_L18N_T2_A23_15,				Sch name = CRAM_DQ10
set_property PACKAGE_PIN G17 [get_ports {data[10]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:376
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[10]' has been applied to the port object 'data[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[10]}]
#Bank = 14, Pin name = IO_L4N_T0_D05_14,					Sch name = CRAM_DQ11
set_property PACKAGE_PIN M18 [get_ports {data[11]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:379
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[11]' has been applied to the port object 'data[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[11]}]
#Bank = 14, Pin name = IO_L10N_T1_D15_14,					Sch name = CRAM_DQ12
set_property PACKAGE_PIN M17 [get_ports {data[12]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:382
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[12]' has been applied to the port object 'data[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[12]}]
#Bank = 14, Pin name = IO_L9N_T1_DQS_D13_14,				Sch name = CRAM_DQ13
set_property PACKAGE_PIN P18 [get_ports {data[13]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:385
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[13]' has been applied to the port object 'data[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[13]}]
#Bank = 14, Pin name = IO_L9P_T1_DQS_14,					Sch name = CRAM_DQ14
set_property PACKAGE_PIN N17 [get_ports {data[14]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:388
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[14]' has been applied to the port object 'data[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[14]}]
#Bank = 14, Pin name = IO_L12P_T1_MRCC_14,					Sch name = CRAM_DQ15
set_property PACKAGE_PIN P17 [get_ports {data[15]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:391
# The conversion of 'IOSTANDARD' constraint on 'net' object 'data[15]' has been applied to the port object 'data[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {data[15]}]

#Bank = 15, Pin name = IO_L23N_T3_FWE_B_15,					Sch name = CRAM_A0
set_property PACKAGE_PIN J18 [get_ports {address[0]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:395
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[0]' has been applied to the port object 'address[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[0]}]
#Bank = 15, Pin name = IO_L18P_T2_A24_15,					Sch name = CRAM_A1
set_property PACKAGE_PIN H17 [get_ports {address[1]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:398
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[1]' has been applied to the port object 'address[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[1]}]
#Bank = 15, Pin name = IO_L19N_T3_A21_VREF_15,				Sch name = CRAM_A2
set_property PACKAGE_PIN H15 [get_ports {address[2]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:401
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[2]' has been applied to the port object 'address[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[2]}]
#Bank = 15, Pin name = IO_L23P_T3_FOE_B_15,					Sch name = CRAM_A3
set_property PACKAGE_PIN J17 [get_ports {address[3]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:404
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[3]' has been applied to the port object 'address[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[3]}]
#Bank = 15, Pin name = IO_L13P_T2_MRCC_15,					Sch name = CRAM_A4
set_property PACKAGE_PIN H16 [get_ports {address[4]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:407
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[4]' has been applied to the port object 'address[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[4]}]
#Bank = 15, Pin name = IO_L24P_T3_RS1_15,					Sch name = CRAM_A5
set_property PACKAGE_PIN K15 [get_ports {address[5]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:410
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[5]' has been applied to the port object 'address[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[5]}]
#Bank = 15, Pin name = IO_L17P_T2_A26_15,					Sch name = CRAM_A6
set_property PACKAGE_PIN K13 [get_ports {address[6]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:413
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[6]' has been applied to the port object 'address[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[6]}]
#Bank = 14, Pin name = IO_L11P_T1_SRCC_14,					Sch name = CRAM_A7
set_property PACKAGE_PIN N15 [get_ports {address[7]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:416
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[7]' has been applied to the port object 'address[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[7]}]
#Bank = 14, Pin name = IO_L16N_T2_SRCC-14,					Sch name = CRAM_A8
set_property PACKAGE_PIN V16 [get_ports {address[8]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:419
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[8]' has been applied to the port object 'address[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[8]}]
#Bank = 14, Pin name = IO_L22P_T3_A05_D21_14,				Sch name = CRAM_A9
set_property PACKAGE_PIN U14 [get_ports {address[9]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:422
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[9]' has been applied to the port object 'address[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[9]}]
#Bank = 14, Pin name = IO_L22N_T3_A04_D20_14,				Sch name = CRAM_A10
set_property PACKAGE_PIN V14 [get_ports {address[10]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:425
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[10]' has been applied to the port object 'address[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[10]}]
#Bank = 14, Pin name = IO_L20N_T3_A07_D23_14,				Sch name = CRAM_A11
set_property PACKAGE_PIN V12 [get_ports {address[11]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:428
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[11]' has been applied to the port object 'address[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[11]}]
#Bank = 14, Pin name = IO_L8N_T1_D12_14,					Sch name = CRAM_A12
set_property PACKAGE_PIN P14 [get_ports {address[12]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:431
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[12]' has been applied to the port object 'address[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[12]}]
#Bank = 14, Pin name = IO_L18P_T2_A12_D28_14,				Sch name = CRAM_A13
set_property PACKAGE_PIN U16 [get_ports {address[13]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:434
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[13]' has been applied to the port object 'address[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[13]}]
#Bank = 14, Pin name = IO_L13N_T2_MRCC_14,					Sch name = CRAM_A14
set_property PACKAGE_PIN R15 [get_ports {address[14]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:437
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[14]' has been applied to the port object 'address[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[14]}]
#Bank = 14, Pin name = IO_L8P_T1_D11_14,					Sch name = CRAM_A15
set_property PACKAGE_PIN N14 [get_ports {address[15]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:440
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[15]' has been applied to the port object 'address[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[15]}]
#Bank = 14, Pin name = IO_L11N_T1_SRCC_14,					Sch name = CRAM_A16
set_property PACKAGE_PIN N16 [get_ports {address[16]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:443
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[16]' has been applied to the port object 'address[16]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[16]}]
#Bank = 14, Pin name = IO_L6N_T0_D08_VREF_14,				Sch name = CRAM_A17
set_property PACKAGE_PIN M13 [get_ports {address[17]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:446
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[17]' has been applied to the port object 'address[17]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[17]}]
#Bank = 14, Pin name = IO_L18N_T2_A11_D27_14,				Sch name = CRAM_A18
set_property PACKAGE_PIN V17 [get_ports {address[18]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:449
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[18]' has been applied to the port object 'address[18]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[18]}]
#Bank = 14, Pin name = IO_L17P_T2_A14_D30_14,				Sch name = CRAM_A19
set_property PACKAGE_PIN U17 [get_ports {address[19]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:452
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[19]' has been applied to the port object 'address[19]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[19]}]
#Bank = 14, Pin name = IO_L24N_T3_A00_D16_14,				Sch name = CRAM_A20
set_property PACKAGE_PIN T10 [get_ports {address[20]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:455
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[20]' has been applied to the port object 'address[20]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[20]}]
#Bank = 14, Pin name = IO_L10P_T1_D14_14,					Sch name = CRAM_A21
set_property PACKAGE_PIN M16 [get_ports {address[21]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:458
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[21]' has been applied to the port object 'address[21]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[21]}]
#Bank = 14, Pin name = IO_L23N_T3_A02_D18_14,				Sch name = CRAM_A22
set_property PACKAGE_PIN U13 [get_ports {address[22]}]
# /home/joel/Documents/hejhej/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/planAhead/leon3-digilent-nexys4/leon3-digilent-nexys4.runs/impl_1/.constrs/leon3mp.ucf:461
# The conversion of 'IOSTANDARD' constraint on 'net' object 'address[22]' has been applied to the port object 'address[22]'.
set_property IOSTANDARD LVCMOS33 [get_ports {address[22]}]


set_property IOSTANDARD LVCMOS33 [get_ports {jb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {jb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {jb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {jb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {jb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {jb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {jb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {jb[0]}]


set_property PACKAGE_PIN V11 [get_ports {jb[2]}]
set_property PACKAGE_PIN P15 [get_ports {jb[1]}]
set_property PACKAGE_PIN G14 [get_ports {jb[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_in[0]}]
set_property PACKAGE_PIN F15 [get_ports {buttons_in[0]}]
set_property PACKAGE_PIN E16 [get_ports {buttons_in[2]}]
set_property PACKAGE_PIN R10 [get_ports {buttons_in[3]}]
set_property PACKAGE_PIN V10 [get_ports {buttons_in[4]}]
set_property PACKAGE_PIN T16 [get_ports {buttons_in[1]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[7]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[6]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[5]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[4]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[3]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[2]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[1]}]
set_property IOSTANDARD LVTTL [get_ports {seven_seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg_out[0]}]
set_property PACKAGE_PIN L3 [get_ports {seven_seg_out[0]}]
set_property PACKAGE_PIN N1 [get_ports {seven_seg_out[1]}]
set_property PACKAGE_PIN L5 [get_ports {seven_seg_out[2]}]
set_property PACKAGE_PIN L4 [get_ports {seven_seg_out[3]}]
set_property PACKAGE_PIN K3 [get_ports {seven_seg_out[4]}]
set_property PACKAGE_PIN M2 [get_ports {seven_seg_out[5]}]
set_property PACKAGE_PIN L6 [get_ports {seven_seg_out[6]}]
set_property PACKAGE_PIN N6 [get_ports {seven_seg_sel[0]}]
set_property PACKAGE_PIN M6 [get_ports {seven_seg_sel[1]}]
set_property PACKAGE_PIN M3 [get_ports {seven_seg_sel[2]}]
set_property PACKAGE_PIN N5 [get_ports {seven_seg_sel[3]}]
set_property PACKAGE_PIN N2 [get_ports {seven_seg_sel[4]}]
set_property PACKAGE_PIN N4 [get_ports {seven_seg_sel[5]}]
set_property PACKAGE_PIN L1 [get_ports {seven_seg_sel[6]}]
set_property PACKAGE_PIN M1 [get_ports {seven_seg_sel[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {diode_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {diode_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {diode_out[0]}]
set_property PACKAGE_PIN F6 [get_ports {diode_out[2]}]
set_property PACKAGE_PIN K5 [get_ports {diode_out[1]}]
set_property PACKAGE_PIN F13 [get_ports {diode_out[0]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
