# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2L
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property constrs_type UCF [current_fileset -constrset]

read_ip c:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/project_1/project_1.srcs/sources_1/ip/DMC/DMC.xco
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/project_1/project_1.srcs/sources_1/ip/DMC/DMC.xco]

read_ip c:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/project_1/project_1.srcs/sources_1/ip/ADC/ADC.xco
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/project_1/project_1.srcs/sources_1/ip/ADC/ADC.xco]

read_vhdl {
  C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/PWM.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/modules.vhd
  C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/top.vhd
}
set_property webtalk.parent_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/project_1/project_1.data/wt [current_project]
set_property parent.project_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/DAC/project_1 [current_project]
synth_design -top top -part xc7a100tcsg324-2L
write_checkpoint top.dcp
report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb
