######################################################################
##
## Filename: Throughput_top.udo
## Created on: Mon Feb 24 12:50:29 2014
##
##  Auto generated by Vivado for Post-implementation Simulation
##
##  You may want to edit this file to control the simulation
##
######################################################################
