######################################################################
##
## Filename: Throughput_top.do
## Created on: Mon Feb 24 12:50:29 2014
##
##  Auto generated by Vivado for Post-implementation Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the simulation directory and will not be removed on
##  subsequent simulation flow runs from Vivado.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#

#
# Create work library
#
vlib work

#
# Map libraries
#

#
# Design sources
#
vcom -work work "C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC/ADC.sim/sim_1/impl/func/Throughput_top_func_impl.vhd"



#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps -L secureip -lib work Throughput_top

#
# Source wave do file
#
do {Throughput_top_wave.do}

#
# Set the window types
#
view wave
view structure
view signals

#
# Source user do file (UDO)
#
do {Throughput_top.udo}

#
# Run simulation for this time
#
run 1000ns


#
# End
#
