# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/joel/leon3.xdc

# IP: ip/fir_compiler_0/fir_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0}]
