# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl -library grlib {
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/version.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/config_types.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/stdlib.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/config.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/amba/amba.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/sparc/sparc.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/modgen/multlib.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/modgen/leaves.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/amba/devices.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/amba/ahbmst.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/amba/apbctrl.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/grlib/amba/ahbctrl.vhd
}
read_vhdl -library techmap {
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/gencomp/gencomp.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allclkgen.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/inferred/memory_inferred.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/memory_unisim.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/grgates.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allmem.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram_2p.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allmul.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/inferred/mul_inferred.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/techmult.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/regfile_3p.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/clkgen_unisim.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/buffer_unisim.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram_dp.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram64.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/grlfpw_net.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/grfpw_net.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/gencomp/netcomp.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/tap_unisim.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/techbuf.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/clkmux.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/clkand.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/alltap.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/pads_unisim.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/tap.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncreg.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncrambw.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allpads.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/outpad.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/iopad.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/inpad.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/techmap/maps/clkgen.vhd
}
read_vhdl -library gaisler {
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmuconfig.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmuiface.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3/leon3.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmulrue.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/libmmu.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libfpu.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/arith/arith.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmutlbcam.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmulru.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libiu.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmutw.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmutlb.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libcache.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmu.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_icache.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_dcache.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_acache.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libleon3.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/uart.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/net/net.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/misc.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/regfile_3p_l3.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_cache.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/iu3.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/arith/mul32.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/arith/div32.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/libdcom.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/memctrl/memctrl.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/tbufmem.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/proc3.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/grlfpwx.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/grfpwxsh.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/grfpwx.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/cachemem.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/libjtagcom.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/ethernet_mac.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/dcom_uart.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/dcom.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/memctrl/sdmctrl.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/leon3x.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/dsu3x.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/jtagcom2.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/jtagcom.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/jtag.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/greth_gbit.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/greth.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/apbuart.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/ahbuart.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/spi/spi.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/rstgen.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/gptimer.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/ahbram.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/leon3s.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/dsu3.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/ahbjtag.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/irqmp/irqmp.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/grethm.vhd
}
read_vhdl -library eth {
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/core/greth_pkg.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/core/eth_rstgen.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/core/greth_tx.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/core/greth_rx.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/core/eth_edcl_ahb_mst.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/core/eth_ahb_mst.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/core/grethc.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/eth/comp/ethcomp.vhd
}
read_vhdl -library esa {
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/esa/memoryctrl/memoryctrl.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/lib/esa/memoryctrl/mctrl.vhd
}
read_vhdl {
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/config.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/ahbrom.vhd
  /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/leon3mp.vhd
}
read_xdc /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/vivado/leon3-digilent-nexys4/leon3-digilent-nexys4.srcs/constrs_1/imports/digilent-nexys4-xc7a100t/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/vivado/leon3-digilent-nexys4/leon3-digilent-nexys4.srcs/constrs_1/imports/digilent-nexys4-xc7a100t/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/vivado/leon3-digilent-nexys4/leon3-digilent-nexys4.data/wt [current_project]
set_property parent.project_dir /home/joel/Documents/DAT096/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/vivado/leon3-digilent-nexys4 [current_project]
synth_design -top leon3mp -part xc7a100tcsg324-2
write_checkpoint leon3mp.dcp
report_utilization -file leon3mp_utilization_synth.rpt -pb leon3mp_utilization_synth.pb
