######################################################################
##
## Filename: Throughput_top.udo
## Created on: Mon Feb 24 12:16:50 2014
##
##  Auto generated by Vivado for Post-synthesis Simulation
##
##  You may want to edit this file to control the simulation
##
######################################################################
