# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
set_property use_blackbox_stub false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
read_verilog c:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_stub.v
read_vhdl C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.srcs/sources_1/new/XADC_interface.vhd
read_xdc C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572/ADC572.data/wt [current_project]
set_property parent.project_dir C:/CHALMERS/DAT096/DAT096/ADCDAC/ADC572 [current_project]
synth_design -top XADC_interface -part xc7a100tcsg324-1
write_checkpoint XADC_interface.dcp
report_utilization -file XADC_interface_utilization_synth.rpt -pb XADC_interface_utilization_synth.pb
